workflows:
  build:
    name: Build App
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Analyze Code
        script: flutter analyze
      - name: Run Tests
        script: flutter test
      - name: Build Android APK
        script: |
          flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - ilauret@somniosoftware.com
        notify:
          success: true
          failure: true
