workflows:
  build:
    name: Build Prod APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
      cancel_previous_builds: true
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Analyze Code
        script: flutter analyze
      - name: Run Tests
        script: flutter test
      - name: Build Android APK
        script: |
          flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - ilauret@somniosoftware.com
        notify:
          success: true
          failure: true
  build:
    name: Build Feature Branch PR
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
          source: false
      cancel_previous_builds: true
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Analyze Code
        script: flutter analyze
      - name: Run Tests
        script: flutter test
      - name: Build Android APK
        script: |
          flutter build apk
      - name: Generate release note with Git commit message
        script: |
          echo "$CM_BRANCH" | tee release_notes.txt
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - release_notes.txt
    publishing:
      email:
        recipients:
          - ilauret@somniosoftware.com
        notify:
          success: true
          failure: true
